safe:       true
lsi:        false
pygments:   true
permalink:  /blog/:title.html

# Blog
author:
    name: Olivier Dolbeau
    email: odolbeau@gmail.com
title: Olivier Dolbeau
description: Web Developer, Symfony2 fan, beer lover.

feedburner:
    id: odolbeau

github:
    username: odolbeau
    blog_repo: odolbeau.github.com

google_analytics:
    account: UA-10214242-1

rss:
    title: Olivier Dolbeau
