safe: true
lsi: false
highlighter: pygments
permalink:  /blog/:title.html
markdown: kramdown

# Blog
author:
    name: Olivier Dolbeau
    email: odolbeau@gmail.com
title: Olivier Dolbeau
description: Web Developer, Symfony2 fan, be[a|e]r lover.

feedburner:
    id: odolbeau

github:
    username: odolbeau
    blog_repo: odolbeau.github.com

google_analytics:
    account: UA-10214242-1

rss:
    title: Olivier Dolbeau
